USE [master]
GO

/****** Object:  Database [UTILS]    Script Date: 3/8/2020 9:40:00 PM ******/
CREATE DATABASE [UTILS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UTILS', FILENAME = N'C:\SQLDATA\UTILS.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'UTILS_log', FILENAME = N'C:\SQLDATA\UTILS_log.ldf' , SIZE = 2304KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [UTILS] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UTILS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [UTILS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [UTILS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [UTILS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [UTILS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [UTILS] SET ARITHABORT OFF 
GO

ALTER DATABASE [UTILS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [UTILS] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [UTILS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [UTILS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [UTILS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [UTILS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [UTILS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [UTILS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [UTILS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [UTILS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [UTILS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [UTILS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [UTILS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [UTILS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [UTILS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [UTILS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [UTILS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [UTILS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [UTILS] SET RECOVERY FULL 
GO

ALTER DATABASE [UTILS] SET  MULTI_USER 
GO

ALTER DATABASE [UTILS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [UTILS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [UTILS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [UTILS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [UTILS] SET  READ_WRITE 
GO


